[package]
name = "rIdentD"
version = "0.1.0"
edition = "2024"
build = "build.rs"
license = "AGPL-3.0-or-later OR GPL-3.0-or-later"

[lib]
name = "ridentd"

[dependencies]
libc = "0.2"
mio = { version = "0.8", default-features = false, features = ["os-poll", "net"] }
num_cpus = "1"
